ignore = [".devenv", "target"]

[modules.rust]
source = "github.com/sagikazarmark/daggerverse-beta/rust"
check.skip = ["audit"]

[modules.rust.settings]
version = "1.97-slim-trixie"

[modules.dagger-gha]
source = "github.com/sagikazarmark/daggerverse-beta/dagger-gha"

[modules.dagger-gha.settings]
lock = '"PINNED"'
