ignore = [".devenv", "target"]

[modules.rust]
source = "github.com/sagikazarmark/daggerverse-beta/rust"
check.skip = ["audit"]

[modules.rust.settings]
version = "1.98-slim-trixie"

[modules.dagger-gha]
source = "github.com/sagikazarmark/daggerverse-beta/dagger-gha"

settings.daggerCommit = "3e485b3ed23dd5a57417a23fe0a9f01ec7858231"
